import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StudentsPage from "./studentTable/page";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Link href="/studentTable" className="absolute top-4 right-4 bg-blue-500 text-white px-4 py-2 rounded mb-10">
          Previous test results
        </Link>
        {children}
      </body>
    </html>
  );
}
